/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#F2EDE2',
        panel: '#FBF7EE',
        'panel-bright': '#FFFDF6',
        field: '#FFFEF9',
        ink: '#211E19',
        'ink-hover': '#3A352C',
        'ink-soft': '#4A463C',
        muted: '#8B8375',
        faint: '#B3AB9B',
        'faint-2': '#C7BEAC',
        line: '#E4DAC7',
        'line-2': '#DDD2BC',
        'line-soft': '#EDE4D0',
        hover: '#F3EDDD',
        'hover-deep': '#E9E1D0',
        fill: '#211E19',
        dot: '#3B362B',
        'dot-off': '#E6DCC5',
        track: '#E7DDC8',
        accent: '#C8512F',
        'accent-deep': '#B34526',
        'accent-soft': '#D89A7E',
        'accent-contrast': '#FFF6EE',
        'accent-tint': '#F0DCCF',
        paper: '#F7F2E7',
        chip: '#EEE6D3',
        'chip-ink': '#6B6455',
        warn: '#A05A2C',
        'warn-tint': '#F3E3D2',
      },
      borderRadius: {
        card: '14px',
        field: '9px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(70,55,30,.06)',
        today: '0 2px 8px rgba(160,85,45,.10)',
      },
      fontFamily: {
        disp: ['Fraunces', 'Georgia', 'serif'],
        ui: ['Inter', '-apple-system', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
