/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#FAF9F7',
        panel: '#FFFFFF',
        'panel-bright': '#FFFFFF',
        field: '#FFFFFF',
        ink: '#211E19',
        'ink-hover': '#3A352C',
        'ink-soft': '#4A463C',
        muted: '#85817A',
        faint: '#B0ACA4',
        'faint-2': '#C9C5BD',
        line: '#EAE8E3',
        'line-2': '#DEDBD3',
        'line-soft': '#F0EEE9',
        hover: '#F4F3EF',
        'hover-deep': '#EBE9E3',
        fill: '#211E19',
        dot: '#3B362B',
        'dot-off': '#E8E6DF',
        track: '#EFEDE7',
        accent: '#C8512F',
        'accent-deep': '#B34526',
        'accent-soft': '#D89A7E',
        'accent-contrast': '#FFF6EE',
        'accent-tint': '#F5E3DA',
        paper: '#FAF9F7',
        chip: '#F1EFEA',
        'chip-ink': '#6E6A61',
        warn: '#A05A2C',
        'warn-tint': '#F6EADF',
      },
      borderRadius: {
        card: '14px',
        field: '9px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(30,28,22,.05)',
        today: '0 2px 6px rgba(30,28,22,.07)',
      },
      fontFamily: {
        disp: ['Fraunces', 'Georgia', 'serif'],
        ui: ['Inter', '-apple-system', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
